# -*- coding: utf-8 -*-
"""Investment Dashboard

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rYwcTi424Yajqr2nNviysNW4f94pl8PQ
"""

import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.express as px
from datetime import date, datetime, timedelta
import yfinance as yf
from IPython.display import display, Markdown

# ============================================================================
# 1. PORTFOLIO CONFIGURATION
#    Edit this section to change instruments, amounts, or debt assumptions.
# ============================================================================

EQUITY_HOLDINGS = [
    # name,                     ticker (NSE),   sector,                 invested_amount (Rs)
    ("Maruti Suzuki India",     "MARUTI.NS",    "Automobile",           900000),
    ("Tata Consultancy Services","TCS.NS",      "Information Technology",900000),
    ("Indian Hotels Company",   "INDHOTEL.NS",  "Services & Logistics", 900000),
    ("Amara Raja Energy & Mobility","ARE&M.NS",  "Automobile",          600000),  # yfinance ticker confirmed as ARE&M.NS
    ("Housing & Urban Dev Corp","HUDCO.NS",     "Financial Services",   600000),
    ("Emami",                   "EMAMILTD.NS",  "FMCG",                 600000),
    ("Blue Star",               "BLUESTARCO.NS","Consumer Durables",    600000),
    ("IRCTC",                   "IRCTC.NS",     "Services & Logistics", 600000),
    ("UTI Asset Management",    "UTIAMC.NS",    "Financial Services",   400000),
    ("Newgen Software",         "NEWGEN.NS",    "Information Technology",400000),
    ("Heritage Foods",          "HERITGFOOD.NS","FMCG",                 500000),
]

GOLD_HOLDINGS = [
    ("Nippon India Gold ETF (Gold BeES)", "GOLDBEES.NS", "Gold", 1000000),
]

# Debt instruments don't have a continuous public market price feed the way
# listed equity/ETFs do, so their value is accrued using YTM (simple
# day-count compounding) rather than fetched live. Update `annual_ytm` with
# the actual coupon/YTM of the instrument you actually purchase.
DEBT_HOLDINGS = [
    # name,                              annual_ytm (decimal), invested_amount (Rs)
    ("AAA PSU Bond / Bharat Bond ETF",    0.078,                800000),
    ("AA/AA+ Corporate NCD",              0.098,                700000),
    ("RBI G-Sec / SDL (3-yr)",            0.073,                500000),
]

BENCHMARK_TICKER = "^NSEI"   # Nifty 50 index

# ============================================================================
# 2. DATA FETCHING (cached so we don't hammer Yahoo Finance on every rerun)
# ============================================================================

def fetch_price_history(tickers, start_date):
    """Download daily adjusted close price history for a list of tickers."""
    end = date.today() + timedelta(days=1)
    data = yf.download(tickers, start=start_date, end=end, progress=False)
    if isinstance(data.columns, pd.MultiIndex):
        close = data["Close"]
    else:
        close = data[["Close"]]
        close.columns = tickers
    return close.dropna(how="all")


def get_entry_and_current_price(price_series, start_date):
    """Entry price = first available close on/after start_date. Current = last available close."""
    series = price_series.dropna()
    if series.empty:
        return None, None
    entry_idx = series.index[series.index >= pd.Timestamp(start_date)]
    entry_price = series[entry_idx[0]] if len(entry_idx) > 0 else series.iloc[0]
    current_price = series.iloc[-1]
    return float(entry_price), float(current_price)


def accrued_debt_value(invested, annual_ytm, start_date):
    """Simple compounding accrual: value = invested * (1 + ytm)^(days/365).
    This is an approximation for tracking purposes only — real bond mark-to-market
    value can differ due to interest rate moves, unless held to maturity."""
    days_elapsed = (date.today() - start_date).days
    days_elapsed = max(days_elapsed, 0)
    return invested * (1 + annual_ytm) ** (days_elapsed / 365)

# --- Hardcode start_date for Colab (equivalent to Streamlit's st.sidebar.date_input) ---
start_date = date.today() - timedelta(days=1)

# Note: Debt instrument values are accrued using their YTM
# (not a live market feed). Equity & gold prices are pulled from Yahoo Finance.

"""# 📊 Investment Portfolio Dashboard

Tracking a ₹1 Cr, 15-instrument portfolio (Equity / Debt / Gold) against a Nifty 50 benchmark.
"""

# --- Fetch equity + gold price data ---
all_market_tickers = [t for _, t, _, _ in EQUITY_HOLDINGS] + [t for _, t, _, _ in GOLD_HOLDINGS]
all_tickers_incl_benchmark = all_market_tickers + [BENCHMARK_TICKER]

print("Fetching live and historical prices...")
price_history = fetch_price_history(all_tickers_incl_benchmark, start_date)
print("Price fetching complete.")

"""## 4. Build Holdings Table"""

rows = []

# Equity
for name, ticker, sector, invested in EQUITY_HOLDINGS:
    if ticker not in price_history.columns:
        print(f"Warning: No price data found for {ticker} — check ticker symbol.")
        continue
    entry_price, current_price = get_entry_and_current_price(price_history[ticker], start_date)
    if entry_price is None:
        print(f"Warning: Not enough historical data for {ticker} from {start_date}.")
        continue
    qty = invested / entry_price
    current_value = qty * current_price
    rows.append({
        "Instrument": name, "Sleeve": "Equity", "Sector": sector,
        "Invested (₹)": invested, "Entry Price": entry_price, "Current Price": current_price,
        "Quantity": qty, "Current Value (₹)": current_value,
    })

# Gold
for name, ticker, sector, invested in GOLD_HOLDINGS:
    if ticker not in price_history.columns:
        print(f"Warning: No price data found for {ticker} — check ticker symbol.")
        continue
    entry_price, current_price = get_entry_and_current_price(price_history[ticker], start_date)
    if entry_price is None:
        print(f"Warning: Not enough historical data for {ticker} from {start_date}.")
        continue
    qty = invested / entry_price
    current_value = qty * current_price
    rows.append({
        "Instrument": name, "Sleeve": "Gold", "Sector": sector,
        "Invested (₹)": invested, "Entry Price": entry_price, "Current Price": current_price,
        "Quantity": qty, "Current Value (₹)": current_value,
    })

# Debt (accrued, not price-fetched)
for name, ytm, invested in DEBT_HOLDINGS:
    current_value = accrued_debt_value(invested, ytm, start_date)
    rows.append({
        "Instrument": name, "Sleeve": "Debt", "Sector": "Fixed Income",
        "Invested (₹)": invested, "Entry Price": np.nan, "Current Price": np.nan,
        "Quantity": np.nan, "Current Value (₹)": current_value,
    })

holdings = pd.DataFrame(rows)
holdings["Absolute Return (₹)"] = holdings["Current Value (₹)"] - holdings["Invested (₹)"]
holdings["Return (%)"] = (holdings["Absolute Return (₹)"] / holdings["Invested (₹)"]) * 100

"""## 5. Portfolio-Level Summary"""

total_invested = holdings["Invested (₹)"].sum()
total_current = holdings["Current Value (₹)"].sum()
total_abs_return = total_current - total_invested
total_pct_return = (total_abs_return / total_invested) * 100
days_held = max((date.today() - start_date).days, 1)
annualized_return = ((total_current / total_invested) ** (365 / days_held) - 1) * 100

# Benchmark (Nifty 50) return over same period
nifty_series = price_history[BENCHMARK_TICKER].dropna()
nifty_entry, nifty_current = get_entry_and_current_price(nifty_series, start_date)
nifty_pct_return = ((nifty_current - nifty_entry) / nifty_entry) * 100 if nifty_entry else np.nan

summary_data = {
    "Metric": [
        "Total Invested",
        "Current Value",
        "Absolute Return",
        "Annualized Return",
        "Nifty 50 Return (same period)",
        "vs Nifty"
    ],
    "Value": [
        f"₹{total_invested:,.0f}",
        f"₹{total_current:,.0f} ({total_pct_return:+.2f}%)",
        f"₹{total_abs_return:,.0f}",
        f"{annualized_return:.2f}%",
        f"{nifty_pct_return:+.2f}%",
        f"{total_pct_return - nifty_pct_return:+.2f}%"
    ]
}
summary_df = pd.DataFrame(summary_data)
display(summary_df)

"""## 6. Portfolio Value vs Nifty 50 — Cumulative Return Chart"""

# Build daily portfolio value time series (equity+gold priced daily, debt accrued daily)
market_price_df = price_history[all_market_tickers].dropna(how="all")
market_price_df = market_price_df.ffill()

portfolio_daily_value = pd.Series(0.0, index=market_price_df.index)

for name, ticker, sector, invested in EQUITY_HOLDINGS + GOLD_HOLDINGS:
    if ticker not in market_price_df.columns:
        continue
    series = market_price_df[ticker]
    entry_idx = series.index[series.index >= pd.Timestamp(start_date)]
    if len(entry_idx) == 0:
        continue
    entry_price = series[entry_idx[0]]
    qty = invested / entry_price
    portfolio_daily_value = portfolio_daily_value.add(series * qty, fill_value=0)

for name, ytm, invested in DEBT_HOLDINGS:
    debt_series = pd.Series(
        [invested * (1 + ytm) ** (max((d.date() - start_date).days, 0) / 365) for d in market_price_df.index],
        index=market_price_df.index,
    )
    portfolio_daily_value = portfolio_daily_value.add(debt_series, fill_value=0)

portfolio_indexed = (portfolio_daily_value / portfolio_daily_value.iloc[0]) * 100
nifty_indexed = (nifty_series.reindex(portfolio_daily_value.index).ffill() / nifty_series.iloc[0]) * 100

fig_compare = go.Figure()
fig_compare.add_trace(go.Scatter(x=portfolio_indexed.index, y=portfolio_indexed,
                                  name="Portfolio", line=dict(color="#2E86AB", width=2.5)))
fig_compare.add_trace(go.Scatter(x=nifty_indexed.index, y=nifty_indexed,
                                  name="Nifty 50", line=dict(color="#A23B72", width=2, dash="dash")))
fig_compare.update_layout(height=420, xaxis_title="Date", yaxis_title="Indexed Value (Start = 100)",
                           hovermode="x unified", legend=dict(orientation="h", y=1.05))

display(fig_compare)

"""## 7. Portfolio Allocation"""

sleeve_alloc = holdings.groupby("Sleeve")["Current Value (₹)"].sum().reset_index()
fig_sleeve = px.pie(sleeve_alloc, names="Sleeve", values="Current Value (₹)",
                     title="By Asset Class (Current Value)", hole=0.45,
                     color_discrete_sequence=["#2E86AB", "#F18F01", "#C73E1D"])
display(fig_sleeve)

sector_alloc = holdings.groupby("Sector")["Current Value (₹)"].sum().reset_index()
fig_sector = px.pie(sector_alloc, names="Sector", values="Current Value (₹)",
                     title="By Sector (Current Value)", hole=0.45)
display(fig_sector)

"""## 8. Individual Instrument Performance"""

display_df = holdings.copy()
for col in ["Invested (₹)", "Current Value (₹)", "Absolute Return (₹)"]:
    display_df[col] = display_df[col].round(0)
display_df["Entry Price"] = display_df["Entry Price"].round(2)
display_df["Current Price"] = display_df["Current Price"].round(2)
display_df["Quantity"] = display_df["Quantity"].round(2)
display_df["Return (%)"] = display_df["Return (%)"].round(2)

def color_returns(val):
    if pd.isna(val):
        return ""
    color = "#1a7f37" if val >= 0 else "#c92a2a"
    return f"color: {color}; font-weight: 600"

styled = display_df.sort_values("Return (%)", ascending=False).style.map(
    color_returns, subset=["Absolute Return (₹)", "Return (%)"]
).format({
    "Invested (₹)": "₹{:,.0f}", "Current Value (₹)": "₹{:,.0f}",
    "Absolute Return (₹)": "₹{:,.0f}", "Return (%)": "{:+.2f}%",
    "Entry Price": "{:.2f}", "Current Price": "{:.2f}", "Quantity": "{:.2f}",
})

display(styled)

display(Markdown("#### Return (%) by Instrument"))
fig_bar = px.bar(
    display_df.sort_values("Return (%)"),
    x="Return (%)", y="Instrument", orientation="h", color="Sleeve",
    color_discrete_sequence=["#2E86AB", "#F18F01", "#C73E1D"],
)
fig_bar.update_layout(height=500)
display(fig_bar)

"""---  
*Data as of {{ datetime.now().strftime('%d %b %Y, %H:%M') }} | Equity & Gold prices: Yahoo Finance (yfinance) | Debt instruments: accrued via YTM, not live-priced | Not investment advice — for personal tracking only.*

## Making Your Dashboard Accessible Regularly

To access this dashboard regularly as a web application, you can follow these steps:

1.  **Save this Colab notebook to GitHub:**
    *   Go to `File > Save a copy in GitHub`. You'll need to connect your GitHub account if you haven't already.
    *   Choose a repository and a file name (e.g., `portfolio_dashboard.py`).

2.  **Ensure your GitHub repository is public.**

3.  **Use a deployment platform like Streamlit Sharing:**
    *   **Create a `requirements.txt` file:** In the same GitHub repository, create a file named `requirements.txt`. This file should list all the Python libraries your dashboard uses. For this dashboard, it would include:
        ```
        streamlit
        yfinance
        pandas
        numpy
        plotly
        ```
    *   **Go to Streamlit Sharing:** Visit [share.streamlit.io](https://share.streamlit.io/) and log in with your GitHub account.
    *   **Deploy your app:** Click on "New app", select your GitHub repository and the `portfolio_dashboard.py` file. Streamlit Sharing will automatically build and deploy your application.

Once deployed, you will get a public URL for your dashboard that you can access anytime, anywhere. Any updates you push to your GitHub repository will automatically update the deployed Streamlit app.
"""